services:
  - type: web
    name: mqa-site
    env: static
    buildCommand: echo "ğŸ—ï¸ Estou dentro do render.yaml" && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /teste-forcado
        destination: /index.html
